README.rdoc
The README says to specific a specific version in the Gemfile but then lists "6.x" and doesn't spell out what versions are available in the 6.x area.  I added a small blurb on how to display all available versions.
=> README change to convey finding available versions

lib/composite_primary_keys/associations/has_and_belongs_to_many_association.rb, test/test_delete.rb
Fixes #273 - habtm association issue when destroying a record.
Let say we have a Foo record that has-and-belongs-to-many Bar records. When we destroy Foo record, the association data in the junction table bars_foos doesn't get deleted. On closer inspection this happens because of the invalid delete statement which silently fails, e.g.:
```
DELETE FROM `bars_foos` WHERE `bars_foos`.`foo_id` = 1 AND NULL
```
This commit amends the habtm test to fail and demonstrate this bug.
Then it addresses this bug inside the HasAndBelongsToManyAssociation in the #delete_records. It makes sure only non-empty predicates are used when scoping the to-be-removed records of the junction table.
Consequently a valid delete statement is generated and test passes.
=> Fix habtm association #delete_records

lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb
The `establish_connection` [monkey patch](https://github.com/composite-primary-keys/composite_primary_keys/blob/master/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb#L12) breaks the enhancements introduced in rails  [PR 13463](
https://github.com/rails/rails/pull/13463).
When `DATABASE_URL` is present, the current code ignores additional parameters specified in the database.yml. The fix makes the method signature in the monkey patch similar to the [signature in the rails code](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_handling.rb#L47)
=> Fixed merging database config when DATABASE_URL is set

lib/composite_primary_keys/persistence.rb
This is a bug fix for ar_3.2.x
First reported here [https://github.com/composite-primary-keys/composite_primary_keys/pull/325]
When connecting to different databases using inheritance, the incorrect syntax is being generated when the databases are of different types.
example:
consider the following class NewBase
```ruby
class NewBase < ActiveRecord::Base
self.abstract_class = true
end
```
When first connecting ActiveRecord to mysql and then using NewBase to connect to sqlserver,
sql updates and saves failed because the query generated was using mysql syntax instead of sqlserver.
=> ar_3.2.x Bug Fix: wrong database syntax when using inheritance

lib/composite_primary_keys/persistence.rb
This is a bug fix for ar_4.0.x
First reported here [https://github.com/composite-primary-keys/composite_primary_keys/pull/325]
When connecting to different databases using inheritance, the incorrect syntax is being generated when the databases are of different types.
example:
consider the following class NewBase
```ruby
class NewBase < ActiveRecord::Base
self.abstract_class = true
end
```
When first connecting ActiveRecord to mysql and then using NewBase to connect to sqlserver,
sql updates and saves failed because the query generated was using mysql syntax instead of sqlserver.
=> ar_4.0.x Bug Fix: wrong database syntax when using inheritance

lib/composite_primary_keys/arel/visitors/to_sql.rb
When using composite_primary_keys, Arel::Nodes::In#to_sql throws an exceptions when the left side is a Arel::Nodes::SqlLiteral.
Please see this for a reproducible example:
https://gist.github.com/tye/948de93617e5fa1752a7
If you run it, you'll see the exception:
NoMethodError: undefined method `name' for "(SELECT something FROM some_other_table WHERE id = 1)":Arel::Nodes::SqlLiteral
I am experiencing this problem in certain scenarios using Ransack.
In the reproducible example, you can uncomment my branch and comment out the composite-primary-keys branch to see it passes with the patch I am proposing.
=> NoMethodError: undefined method `name' for ... Arel::Nodes::SqlLiteral

lib/composite_primary_keys/associations/has_many_through_association.rb, test/fixtures/user.rb, test/test_polymorphic.rb
When you have a has_many :through association with a polymorphic source:
```ruby
class User < ActiveRecord::Base
has_many :commenting_users, through: :comments, source: :commenter, source_type: 'User'
end
class Comment < ActiveRecord::Base
belongs_to :commenter, polymorphic: true
end
```
Trying to set the list of associated objects will fail with a "Uninitialized constant" error:
```ruby
User.find(1).update_attributes commenting_users: [User.find(2), User.find(3)]
```
will result in an exception like:
```ruby
NameError: uninitialized constant Comment::Commenter
```
See the test case I added for a working example of this failure.
In the HasManyThroughAssociation#delete_records method we are looking up the source class on the source_reflection. It doesn't make sense to me to ever do this in …
=> "uninitialized constant" when using a has_many through association with a polymorphic source

lib/composite_primary_keys/associations/join_dependency.rb
association_cache method deleted in rails5 that replace ```association_cache.key?``` to ```association_cached?```
=> fix association_cache method missing error

lib/composite_primary_keys.rb, lib/composite_primary_keys/autosave_association.rb, test/test_associations.rb
Without patching ```autosave_association.rb```, below case will fail with error
```TypeError: [:dorm_id, :room_id] is not a symbol nor a string```
```
room = Room.new(dorm_id: 1000, room_id: 1001)
room_assignment = RoomAssignment.new(student_id: 1000)
room_assignment.room = room
room_assignment.save
```
The change is to fix the issue by using ```record.read_attribute``` instead of ```record.send``` in ```autosave_association.rb```.
=> change autosave_association.rb so that association autosave can work

lib/composite_primary_keys.rb, lib/composite_primary_keys/arel/visitors/to_sql.rb, lib/composite_primary_keys/connection_adapters/abstract_mysql_adapter.rb, test/test_delete_all.rb
The change patch Arel so that ```Arel::Attributes::Attribute``` can be handled well when #name is one Array.
It can fix the failure case test_delete_all_with_joins. (SQLite cannot work for this case since multi-column IN clause like (column1, column2) IN (...) is not allowed in SQLite3).
=> Fix failure case test_delete_all_with_joins and make CPK work for Arel::Attributes::Attribute

lib/composite_primary_keys/validations/uniqueness.rb
As corrected in https://github.com/rails/rails/pull/7072
=> Bugfix/ar_4.0.x: read from attribute rather than `send` in uniqueness validation

lib/composite_primary_keys/composite_predicates.rb, test/test_predicates.rb
The creation is done recursively instead of blindly iteratively.
This has the advantage when generating the actual SQL code the
depth of the tree will be a lot smaller (log_2), and as a result
will not generate a stack level too deep problem.
This fixes #320
=> Create OR predicates in a nicely balanced tree.

lib/composite_primary_keys/attribute_methods/read.rb, test/fixtures/db_definitions/postgresql.sql, test/fixtures/pk_called_id.rb, test/fixtures/pk_called_ids.yml, test/test_ids.rb
For tables that have ID column and use composite primary keys, the id attribute
is already overridden to fetch multiple attributes. This change prevents
nesting the entire primary key in the first element for invocations of id,
matching the behavior in the ar_4.1.x branch.
=> Don't nest PK twice when looking up id, fixes #319

lib/composite_primary_keys/relation/calculations.rb
Similar to #283, this pull request fixes `ConnectionNotEstablished` errors when the database connection has been established on a class other than `ActiveRecord::Base`.  The explanation of the use case is the exact same as #283.  I ran into the bug when trying to run `Model.find_each` as opposed to `Model.count` as @wconrad describes.
The merge @wconrad provided was against ActiveRecord 4.1, whereas this one targets ActiveRecord 3.2.  One minor change is that `result.column_types.fetch(column_alias)` threw an undefined method error, so I reverted back to using `column_for(column_name)` as the code did originally.
Since the code is practically the same as the accepted merge of #284, I have not tested it beyond verifying that `Model.find_each` and `Model.count` works correctly.
=> ConnectionNotEstablished error when db connection is on class other than ActiveRecord::Base

test/fixtures/db_definitions/sqlite.sql
The one failing test left on sqlite3 was a mistake in copying pk_called_ids DDL.
=> Fix TestIds#test_set_ids_string

lib/composite_primary_keys/arel/sqlserver.rb
Seems like the branches of the case statement are inverted, fixes https://github.com/composite-primary-keys/composite_primary_keys/issues/383
=> fix incorrect case statement to get PK for SQLServer

tasks/databases/oracle.rake
This pull request addresses `ActiveRecord::StatementInvalid: OCIError: ORA-00900: invalid SQL statement:` when `rake oracle:build_database` command executed:
This is due to rake task was attempting to run empty string. 
```ruby
$ bundle exec rake oracle:build_database
rake aborted!
ActiveRecord::StatementInvalid: OCIError: ORA-00900: invalid SQL statement:
stmt.c:243:in oci8lib_220.so
/home/yahonda/git/composite_primary_keys/tasks/databases/oracle.rake:17:in `block (3 levels) in <top (required)>'
/home/yahonda/git/composite_primary_keys/tasks/databases/oracle.rake:16:in `each'
/home/yahonda/git/composite_primary_keys/tasks/databases/oracle.rake:16:in `block (2 levels) in <top (required)>'
/home/yahonda/.rbenv/versions/2.2.2/bin/bundle:23:in `load' …
```
=> Address ORA-00900 error when it attempts to execute blank statement

test/fixtures/db_definitions/mysql.sql
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
MySQL `Server version: 5.7.17-0ubuntu0.16.10.1 (Ubuntu)`
composite_primary_keys master branch
```ruby
$ rake mysql:build_database
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Invalid default value for 'updated_at':
create table tariffs (
tariff_id int not null,
start_date date not null,
amount integer(11) default null,
created_at timestamp,
updated_at timestamp,
primary key (tariff_id, start_date)
)
/var/lib/gems/2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
/var/lib/gems/2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
/var/lib/gems/2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
/var/lib/gems/2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query' …
```
=> Use `datetime` to address Invalid default value for 'updated_at'

lib/composite_primary_keys/arel/sqlserver.rb
I've just updated primary_Key_From_Table method to match current code base of activerecord-sqlserver-adapter to fix **NameError: undefined local variable or method `schema_cache'**  error.
See https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/620baf2be175cfdb5333aa11c69f8efafb65fff6/lib/arel/visitors/sqlserver.rb#L193-L194
I'm not sure whether it should be merged to master or separate branch. 
Please correct me if I am wrong.
rails (5.1.3)
activerecord-sqlserver-adapter (5.1.1)
=> Fix sqlserver undefined local variable or method `schema_cache'

lib/composite_primary_keys/nested_attributes.rb, test/test_nested_attributes.rb
This fixes #412 by removing `*_will_change!` calls added in #348 via https://github.com/composite-primary-keys/composite_primary_keys/commit/dc0cc456be228748cc0416d7d19d477744dee97a.
Originally `update_attribute` in [Rails 4.2](https://github.com/rails/rails/blob/v4.2.0/activerecord/lib/active_record/persistence.rb#L239) called save no matter if changes existed. [Rails 5.0](https://github.com/rails/rails/blob/v5.0.0/activerecord/lib/active_record/persistence.rb#L255) updated it to only save if `changed?`, and [Rails 5.1](https://github.com/rails/rails/blob/v5.1.0/activerecord/lib/active_record/persistence.rb#L270) updated it to call a new method, `has_changes_to_save?`. The problem is these methods don't return true if only an association was updated, even if the call to save would …
=> Fix Paper Trail compatibility

lib/composite_primary_keys/associations/preloader/association.rb, test/test_preload.rb
Thanks for making this awesome gem.
We had N+1 problem when upgrading to Rails 5.1.5 using composite-primary-keys v10.0.3
Assuming we have `Country` and `City` model and `Country` has_many `City`.
```ruby
countries = Country.preload(:cities)
city = countries.first.cities.first
city.association(:country).loaded? #=> false
city.country # will trigger call to DB
```
Not sure why inversion is not set. The difference lies in these 2 lines: https://github.com/rails/rails/blob/v5.1.5/activerecord/lib/active_record/associations/preloader/association.rb#L63-L64
I noticed that tests failed due to the recent update in `mysql2` from `0.4.10` to `0.5.0` and made a separate PR to address the issue: #434
=> Set inversion when using preload Rails 5.1.x

Gemfile
I noticed it will fail if checking out from `ar_5.1.x` because `mysql2` just updated `0.5.0` recently
Example failed build: https://travis-ci.org/composite-primary-keys/composite_primary_keys/jobs/359215301
=> Lock mysql2 to ~> v0.4.0 for Rails 5.1.x

lib/composite_primary_keys/relation/batches.rb
This is the same concept as used in the main rails code here:
https://github.com/rails/rails/blob/v4.2.10/activerecord/lib/active_record/relation/batches.rb#L128
Before looping to the next iteration of `find_in_batches` we populate the relation to an array.  Without this the `while records.any?` check at the top of the loop ends up performing an extra count query, and at worse it was crashing for me (but that might have been an interaction with another gem I'm using)
=> Convert batches to arrays before continuing loop

lib/composite_primary_keys/relation/finder_methods.rb
[ActiveRecord::Associations::JoinDependency#aliases](https://github.com/rails/rails/commit/50036e673b3b6ff41476814b212b55fabac3a638#diff-06059df8d3dee3101718fb2c01151ad0R134) was made private.
A new method [#apply_column_aliases](https://github.com/rails/rails/commit/50036e673b3b6ff41476814b212b55fabac3a638#diff-06059df8d3dee3101718fb2c01151ad0R126) was added.
At first glance this new method appears to orchestrate a similar interaction as in the call replaced
below.
I submit this commit having checked the postgresql tests. I'll see what else I have available to test... Or hopefully the CI will take it!
Attempts to fix: https://github.com/composite-primary-keys/composite_primary_keys/issues/459
=> API change in AR 5.2.x

lib/composite_primary_keys/associations/preloader/association.rb, test/test_preload.rb
The original implementation passes the key to the `convert_method` before fetching the owner. This commit restores the conversion behaviour.
Haven't figured out a case where this actually applies. Just hit this while trying to make preloading case insensitive by overriding this method :woman_shrugging: 
Not entirely sure what's wrong with the sqlite tests :thinking:
=> Stay close to the original implementation of Association#run

lib/composite_primary_keys/connection_adapters/abstract_mysql_adapter.rb, test/test_update_all.rb
Hi,
We've encountered an error while updating to 8.1.6 (our app is Rails 4).
```
NoMethodError: undefined method `map' for "id":String
Did you mean?  tap
from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/composite_primary_keys-8.1.6/lib/composite_primary_keys/connection_adapters/abstract_mysql_adapter.rb:18:in `subquery_for'
from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:334:in `join_to_update'
from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:354:in `join_to_update'
from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/activerecord-4.2.10/lib/active_re …
```
=> Fix key not being an array in subquery on has_many :through

.travis.yml, Gemfile
This PR updates the CI configuration on the `master` branch:
- use Ruby 2.6.3 in the matrix
- use PostgreSQL 9.4 - Fixes #484 
- remove Ruby 2.4.6 from the matrix - Rails 6 requires at least Ruby 2.5.0, and we're fixed on that version
- remove the no-longer-used Travis setting `sudo: false`. See [more at the Travis blog](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
This makes the build 💚 green.
=> CI: Use 2.6.3, drop 2.4.6 (Rails 6 requires 2.5.0+)

.travis.yml, composite_primary_keys.gemspec, lib/composite_primary_keys/associations/preloader/association.rb, lib/composite_primary_keys/base.rb, lib/composite_primary_keys/composite_arrays.rb, lib/composite_primary_keys/connection_adapters/abstract_adapter.rb, lib/composite_primary_keys/relation/finder_methods.rb, test/fixtures/db_definitions/mysql.sql, test/test_composite_arrays.rb, test/test_find.rb, test/test_ids.rb
The commit fixes an issue when a CPK field contains commas.
Issue: https://github.com/composite-primary-keys/composite_primary_keys/issues/505
CPK is represented by Array or String. Fields in CPK as String are separated by comma. If a CPK field contains a comma, string representation of such CPK is parsed incorrectly. To address the issue,
commas in fields of CPK represented by String are escaped.
=> Fix issue #505 pk with comma

lib/composite_primary_keys/connection_adapters/sqlserver/database_statements.rb
I fixed method arguments for Rails 6 as well as other adapters.
FYI: https://github.com/composite-primary-keys/composite_primary_keys/commit/9a51742b3b3c6c967d3ad2408d80c699dff69be5#diff-52b23807f8898e851aad8bf740baca75
=> Remove extra argument from sql_for_insert

lib/composite_primary_keys/persistence.rb, test/fixtures/cpk_with_default_value.rb, test/fixtures/cpk_with_default_values.yml, test/fixtures/db_definitions/mysql.sql, test/fixtures/db_definitions/oracle.drop.sql, test/fixtures/db_definitions/oracle.sql, test/fixtures/db_definitions/postgresql.sql, test/fixtures/db_definitions/sqlite.sql, test/fixtures/db_definitions/sqlserver.sql, test/test_create.rb
If one of the composite keys have a default value, creating a new record results in the primary key attributes, not being assigned the database generated values from the incremental keys.
This is caused by ActiveRecords behaviour of pre-assigning default values on initialize which conflicts with this library's check of only assigning the primary keys if all of those attributes are nil. 
My tests showcase a scenario where one of the composite keys have an empty string as default value, but the other one is a normal incremental integer (could also be a uuid). This could be useful if you want one of the composite keys to act as the (primary) primary-key, but want to have the option of adding an alternative version for some of the records.
Since no column used as a primary key, can be NULL, …
=> Pk with default values

.travis.yml
**Descriptoin:**
* Add `mysql` service to `.travis.yml`
Fixes error in tests:
```
Mysql2::Error::ConnectionError: Can't connect to local MySQL server
through socket '/var/run/mysqld/mysqld.sock' (2)
```
See https://travis-ci.org/github/composite-primary-keys/composite_primary_keys/builds/654196500
*  Add `postgresql` service to `.travis.yml`
Fixes error in tests:
```
PG::ConnectionBad: could not connect to server: Connection refused
Is the server running on host "localhost" (127.0.0.1) and accepting
TCP/IP connections on port 5432?
```
See https://travis-ci.org/github/composite-primary-keys/composite_primary_keys/builds/661489337
The tests started to run. Some tests fail, they will be fixed in next PRs:
* https://github.com/composite-primary-keys/composite_primary_keys/pull/512
=> Fix .travis.yml to make the tests run

lib/composite_primary_keys/base.rb, lib/composite_primary_keys/composite_arrays.rb, lib/composite_primary_keys/connection_adapters/abstract_adapter.rb, lib/composite_primary_keys/relation/finder_methods.rb, test/test_composite_arrays.rb, test/test_find.rb, test/test_ids.rb
This is a cherry pick of 2dbd7a9bbebc7f584c6ec618c7666e1a9a2e4231 from master.
Original PR: https://github.com/composite-primary-keys/composite_primary_keys/pull/506.
The commit fixes an issue when a CPK field contains commas.
Issue: #505
CPK represented by Array or String. Fields in CPK as String are
separated by comma. If a CPK field contains a comma, string
representation of such CPK is parsed incorrectly. To address the issue,
commas in fields of CPK represented by String are escaped.
=> Fix handling CPK with fields containing comma

composite_primary_keys.gemspec, lib/composite_primary_keys/reflection.rb
In https://github.com/rails/rails/commit/54de9b1e4f5823bf22001be60efcb996ce6d260b (v5.2.4)
`ActiveRecord::Reflection::AbstractReflection#build_join_constraint`
method was removed.
Fixes incorrect SQL condition for joining by CPK.
=> Fix overriding AbstractReflection for activerecord 5.2.4

lib/composite_primary_keys/validations/uniqueness.rb
Ruby 2.7 has deprecated passing the last argument as a keyword parameter. https://bugs.ruby-lang.org/issues/14183
This warning has already been fixed in Rails https://github.com/rails/rails/blob/master/activerecord/lib/active_record/validations/uniqueness.rb#L38
Fixes this deprecation warning
```
/composite_primary_keys/lib/composite_primary_keys/validations/uniqueness.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/rails/activemodel/lib/active_model/errors.rb:395: warning: The called method `add' is defined here
```
The fix is backwards compatible with Ruby < 2.7
=> Remove deprecation warning for Ruby 2.7

lib/composite_primary_keys/persistence.rb, test/fixtures/cpk_with_default_value.rb, test/fixtures/db_definitions/mysql.sql, test/fixtures/db_definitions/oracle.sql, test/fixtures/db_definitions/postgresql.sql, test/fixtures/db_definitions/sqlite.sql, test/fixtures/db_definitions/sqlserver.sql, test/test_create.rb
This fixes the issue when a field in the composite primary key has a default value of `false`.  See #518   
@cfis I kind of googled and updated the different flavors of DBs, but only really tested on mysql.  Perhaps you have some notes i can update this PR with?
=> Closes #518 Fix issue with ORM default false values

lib/composite_primary_keys/connection_adapters/abstract_mysql_adapter.rb, test/test_delete.rb
Within the subquery_for method, 'key' is an array of structs (Arel::Attributes::Attribute) for cpk models and a single struct for non-cpk models. It seems that the code is calling Array(key) assuming that in the case of a single struct you will have an array with one element, which is the struct. Instead, calling [struct.to_a](https://apidock.com/ruby/Struct/to_a) actually takes the struct and turns it into an array, where each field of the array is a field from the struct. Example:
To achieve the intended result, we can instead call [key].flatten. Example:
For reference, here are the same two examples, but with a cpk:
=> Fix subquery_for for non-cpk

README.rdoc
Bundler has [deprecated CLI flags including --without](https://github.com/rubygems/bundler/blob/d4993be66fa2e76b3ca00ea56a51ecab5478b726/UPGRADING.md#cli-deprecations), which is currently in the setup instructions [in the README](https://github.com/composite-primary-keys/composite_primary_keys/blob/master/README.rdoc#tests-).
It also appears you may need to alter your [Travis configs](https://github.com/composite-primary-keys/composite_primary_keys/blob/ac17a99dcfc3a16db9b7b4c9c71234f473b369b3/.travis.yml#L3), though I am not familiar enough with Travis to make the changes.
=> remove deprecated bundler flag --without

lib/composite_primary_keys/relation/finder_methods.rb, test/test_find.rb
The change fixes error on referencing `RecordNotFound` inside `CompositePrimaryKeys::ActiveRecord::FinderMethods`:
```
NameError: uninitialized constant CompositePrimaryKeys::ActiveRecord::FinderMethods::RecordNotFound   
```
=> Fix references to RecordNotFound

lib/composite_primary_keys/connection_adapters/mysql/database_statements.rb
Calling a private method with `self` receiver is supported from ruby 2.7.
In ruby 2.6 it resolves a below error,
```
NoMethodError: private method `column_for' called for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x000055bd449c00e8>
```
refs
- https://github.com/ruby/ruby/pull/2474
- https://bugs.ruby-lang.org/issues/11297
- https://bugs.ruby-lang.org/issues/16123
=> Stay compatible with ruby 2.6 and below

History.rdoc, README.rdoc, composite_primary_keys.gemspec, lib/composite_primary_keys.rb, lib/composite_primary_keys/associations/association_scope.rb, lib/composite_primary_keys/associations/join_dependency.rb, lib/composite_primary_keys/attribute_methods/primary_key.rb, lib/composite_primary_keys/attribute_methods/read.rb, lib/composite_primary_keys/attribute_methods/write.rb, lib/composite_primary_keys/nested_attributes.rb, lib/composite_primary_keys/reflection.rb, lib/composite_primary_keys/relation.rb, lib/composite_primary_keys/relation/batches.rb, lib/composite_primary_keys/relation/calculations.rb, lib/composite_primary_keys/relation/finder_methods.rb, lib/composite_primary_keys/relation/predicate_builder/association_query_value.rb, lib/composite_primary_keys/relation/query_methods.rb, lib/composite_primary_keys/relation/where_clause.rb, lib/composite_primary_keys/table_metadata.rb, lib/composite_primary_keys/version.rb, test/fixtures/departments.yml, test/fixtures/employees.yml, test/test_attributes.rb, test/test_calculations.rb, test/test_delete.rb, test/test_find.rb
Figured I'd share that in case anyone else is looking to start working on this too. 
Other things to do:
=> Upgrade to work on Rails 6.1.3

lib/composite_primary_keys/relation/predicate_builder/association_query_value.rb, test/test_associations.rb
There was an issue when using the association name as a query param but only including its ID as the value, rather than an AR object
@mihaijurca and @LyricL-Gitster and @stevehill1981 if you all wanna check this out. 
@cfis if looks good to you, will you merge?
=> Fix #551 and Fix #554

lib/composite_primary_keys/relation.rb, test/test_delete.rb, test/test_update.rb
When target model connecion is different from ActiveRecord::Base.connection, 
delete_all and update_all raise error.
```
5: from activerecord-6.1.3.2/lib/active_record/querying.rb:22:in `delete_all'
4: from composite_primary_keys-13.0.0/lib/composite_primary_keys/relation.rb:77:in `delete_all'
3: from activerecord-6.1.3.2/lib/arel/tree_manager.rb:55:in `to_sql'
2: from activerecord-6.1.3.2/lib/active_record/connection_handling.rb:283:in `connection'
1: from activerecord-6.1.3.2/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection': No connection pool for 'ActiveRecord::Base' found. (ActiveRecord::ConnectionNotEstablished)
``` …
=> Fix unintentional connection to database

lib/composite_primary_keys/associations/join_dependency.rb, test/fixtures/membership.rb, test/test_associations.rb
Continuation of #560.
There is an SQL generation problem where a scoped association with
composite primary keys gets generated with SQL like:
```
FROM `table1` INNER JOIN `table2` ON  AND
```
ON and AND are not supposed to be next to one another.
This adds a test to uncover the issue, and then fixes it with a patch.
The problem seems to be that `append_constraints` assumes that `right.expr` is non-empty, but in the case of CPK it is sometimes empty, presumably because id constraints have been removed.
Tests passing here: https://github.com/ryantm/composite_primary_keys/pull/2/checks
=> fix scoped associations

composite_primary_keys.gemspec, lib/composite_primary_keys/autosave_association.rb, test/fixtures/department.rb, test/test_associations.rb
Fixed undefined_method error since `record_changed?` has been renamed to `_record_changed?` in ActiveRecord 7.0.2
follow this change: https://github.com/rails/rails/pull/44191
=> Follow the method name change in ActiveRecord 7.0.2

lib/composite_primary_keys/composite_arrays.rb, test/test_composite_arrays.rb
Suppose you have a route like this.
```ruby
get '/friendships/:id', to: 'friendships#show', as: 'friendship'
```
On generating a path using the Rails routing method, passing the model instance works perfectly:
```ruby
app.friendship_path(Friendship.first)
=> "/friendships/1,30"
```
but using the id explicitly produces a different outcome.
```ruby
app.friendship_path(id: Friendship.first.id)
=> "/friendships/1%2F30"
```
This is because `CompositePrimaryKeys::CompositeKeys` inherits from `Array`, and it has [its own `#to_param` in `active_support/core_ext`](https://github.com/rails/rails/blob/8d34f769ceeac75602ef08a5b55f6ea305184f46/activesupport/lib/active_support/core_ext/object/to_query.rb#L42-L44).
This isn't good for us, because the path changes based on how they were generated and …
=> Make CompositeKeys respond to #to_param consistently with ActiveRecord::Base

lib/composite_primary_keys/associations/collection_association.rb, test/test_associations.rb
In the current implementation, we can assign has_many association using composite key ids like
```ruby
room.room_assignment_ids = [[3, 1, 2], [4, 1, 2]]
```
but it doesn't accept the string representation of composite key ids.
```ruby
room.room_assignment_ids = ['3,1,2', '4,1,2']
```
This PR is an attempt to add that capability, with adding some tests.
=> Accept strings in has_many ids assignment

lib/composite_primary_keys/associations/through_association.rb
Hi, thanks for the wonderful gem.
I stumbled upon this error, that's already solved for rails 6.x & 7.x, but since we're still on rails 5.x, I thought of making the fix.
Fixes the issue described in https://github.com/composite-primary-keys/composite_primary_keys/issues/558, for rails 5.2x
=> fix reflection with polymorphic association

History.rdoc, lib/composite_primary_keys/persistence.rb, test/test_create.rb
It was introduced in Rails 6.1.0, so composite-primary-keys should support it in the 13.x series.
https://api.rubyonrails.org/v6.1.0/classes/ActiveRecord/Persistence.html#method-i-previously_new_record-3F
=> ar_6.1.x: Fix previously_new_record? not being set to true after create

.github/workflows/mariadb.yml, .github/workflows/mysql.yml, .github/workflows/postgresql.yml, .github/workflows/sqlite.yml
Also quotes "3.0" to avoid truncation.  An unquoted "3.0" is truncated to "3", which causes the latest Ruby 3 (at this point 3.2.0) to be loaded, which is not what's intended.
This runs green on my fork.
=> Adds Ruby 3.2 to CI.  Updates checkout action versions.

lib/composite_primary_keys/composite_predicates.rb, test/test_predicates.rb
Query generation for cpk_in_predicate now constructs queries in the form:
```sql
SELECT *
FROM table_name
WHERE low_cardinality_key_part = 1 AND high_cardinality_part IN (1, 2)
```
It used to generate queries in the form:
```sql
SELECT *
FROM table_name
WHERE
(low_cardinality_key_part = 1 AND high_cardinality_part = 1)
OR (low_cardinality_key_part = 1 AND high_cardinality_part = 2)
```
This change improves the queries by reducing the overall length of the query, especially when loading many keys. But more importantly the new query will often result in Postgres performing an `Index Scan` instead of a `Bitmap Heap Scan` (assuming the right indices have been added).
=> Improve query generation for cpk_in_predicate

lib/composite_primary_keys/composite_predicates.rb, test/test_predicates.rb
Query generation for cpk_in_predicate now constructs queries in the form:
```
SELECT *
FROM table_name
WHERE low_cardinality_key_part = 1 AND high_cardinality_part IN (1, 2)
```
It used to generate queries in the form:
```
SELECT *
FROM table_name
WHERE
(low_cardinality_key_part = 1 AND high_cardinality_part = 1)
OR (low_cardinality_key_part = 1 AND high_cardinality_part = 2)
```
This change improves the queries by reducing the overall length of the query, especially when loading many keys. But more importantly the new query will often result in Postgres performing an `Index Scan` instead of a `Bitmap Heap Scan` (assuming the right indices have been added).
=> AR 6.1 - Improve query generation for cpk_in_predicate

.github/workflows/mariadb.yml, .github/workflows/mysql.yml, .github/workflows/postgresql.yml, .github/workflows/sqlite.yml, .github/workflows/trilogy.yml
To ensure nothing breaks the trilogy adapter we want there to be a workflow that runs tests against it. So add a GitHub workflow.
I attempted to add this here https://github.com/composite-primary-keys/composite_primary_keys/pull/607 but couldn't get it to work for some reason. When looking at why it works in the docker-compose file it became apparent that we needed to specify a version of mysql `5.7`.  The reason why may be due to [one of these reasons](https://github.com/trilogy-libraries/trilogy/issues?q=is%3Aissue+is%3Aopen+mysql+8+). I didn't spend too much time digging in.
~~I also spend some time to update the array to all be floats, because having a string in the array didn't feel quite right 😄~~ https://github.com/composite-primary-keys/composite_primary_keys/pull/589. I also …
=> Add trilogy GitHub workflow

lib/composite_primary_keys/core.rb, test/test_equal.rb, test/test_hash.rb
Forward port of #617
Related: #616
=> AR 7.0: Fix object comparison for models with composite keys

lib/composite_primary_keys/reflection.rb
Adding scopes after the join relation removes the join query from the generated SQL.
Rearrange code to match [rails 7.0 method](https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/reflection.rb#L175)
Example:
```rb
class User < ApplicationRecord
has_many :features, -> { enabled }
end
class Feature < ApplicationRecord
scope :enabled, -> { where.not(user_id: nil).where(enabled: true) }
end
```
=> Fix scope overriding join relation query

composite_primary_keys.gemspec
[Ruby gems](https://rubygems.org/gems/composite_primary_keys) doesn't show the link to the changelog.
Since the filename is a little unconventional, I have had hard time finding the changelog location.
=> Chore - Add changelog to gemfile
