composite-primary-keys/composite_primary_keys

lib/composite_primary_keys/associations/singular_association.rb
test/fixtures/db_definitions/mysql.sql
test/fixtures/db_definitions/postgresql.sql
test/fixtures/db_definitions/sqlite.sql
test/fixtures/employee.rb
test/fixtures/salary.rb
test/test_associations.rb

Fix has one association executes wrong update query

---

tasks/databases/sqlserver.rake
test/connections/native_sqlserver/connection.rb
test/fixtures/db_definitions/sqlserver.drop.sql
test/fixtures/db_definitions/sqlserver.sql

Make it easier on Windows to run unit tests for sqlserver (still 4 fails left).

Windows sqlserver test setup

---

lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb
lib/composite_primary_keys/relation/batches.rb
test/test_habtm.rb

Fix ArgumentError in rails5.0.0.rc1

---

.gitignore
test/test_associations.rb

When working on #355 I made a change to:
1) allow developers to run the tests without installing gems to work with DBs they don't have
2) restore the tests that had been commented out

Development updates

---

lib/composite_primary_keys/autosave_association.rb

extend approach from #344 to fix autosave for has_one associations as well

---

.gitignore
composite_primary_keys.gemspec
lib/composite_primary_keys/autosave_association.rb
test/fixtures/db_definitions/mysql.sql
test/fixtures/db_definitions/oracle.sql
test/fixtures/db_definitions/postgresql.sql
test/fixtures/db_definitions/sqlite.sql
test/fixtures/db_definitions/sqlserver.sql
test/fixtures/employee.rb
test/fixtures/employees.yml
test/test_associations.rb

Fixing bug in #344 and fixing&adding test for #377

Associations with inverse fix

---

lib/composite_primary_keys/associations/association_scope.rb
test/test_create.rb

Query cache with bind params

---

test/test_preload.rb

Fixes random failures in test_preload_of_polymorphic_association

Tests: add hacks to TestPreload fixtures

---

lib/composite_primary_keys/associations/association_scope.rb

Background
it keeps giving  
`wrong number of arguments (given 4, expected 5)
` due to code changes over  https://github.com/rails/rails/commit/47b2ddd34da7dfabcda06d7fca39c1ca03ea87cc, so after this fix it seems to work 
closes #394

patch so it works on rails 5.1

---

lib/composite_primary_keys/associations/preloader/association.rb
lib/composite_primary_keys/associations/preloader/belongs_to.rb
lib/composite_primary_keys/attribute_methods/write.rb

Update to provide Rails 5.1 compatibility

---

lib/composite_primary_keys.rb
lib/composite_primary_keys/attribute_methods/primary_key.rb
lib/composite_primary_keys/core.rb

This gets the build passing for Rails 5.1.

Update for Rails 5.1

---

lib/composite_primary_keys/nested_attributes.rb
test/test_nested_attributes.rb

This backports the fix for #412 to the 9.x line.

Fix Paper Trail compatibility

---

lib/composite_primary_keys/connection_adapters/sqlserver_adapter.rb

Add ActiveRecord 5.1 support for SQLServerAdapter

---

History.rdoc
lib/composite_primary_keys/version.rb

Following @tomhughes  update in https://github.com/composite-primary-keys/composite_primary_keys/pull/426 would it be possible to release this as 10.0.3?
Many thanks
Ed

Version 10.0.3

---

.travis.yml
Gemfile
composite_primary_keys.gemspec
lib/composite_primary_keys.rb
lib/composite_primary_keys/associations/preloader/association.rb
lib/composite_primary_keys/connection_adapters/postgresql/database_statements.rb
lib/composite_primary_keys/relation.rb

Rails 6.rc1 fixed an issue about preloading associations [here](https://github.com/rails/rails/pull/35496)
I have ported over the changes to the Association class

Use latest Rails 6 rc1

---

lib/composite_primary_keys/attribute_methods.rb

* Prevents infinite loops with gems which modify the 'attributes' method.
* Fixes #526

Implement raw access for attributes

---

.github/workflows/mariadb.yml
.github/workflows/mysql.yml
.github/workflows/postgresql.yml
.github/workflows/sqlite.yml
README.rdoc
composite_primary_keys.gemspec
lib/composite_primary_keys.rb
lib/composite_primary_keys/associations/preloader/association.rb
lib/composite_primary_keys/composite_predicates.rb
lib/composite_primary_keys/persistence.rb
lib/composite_primary_keys/relation/calculations.rb
lib/composite_primary_keys/version.rb
test/abstract_unit.rb

* Update dependencies to AR 7.0 + Ruby 2.7
Many more commits to come. If anyone wants to help make the tests pass, please feel free to send PRs to my fork so I can pull them in as I work on them too.

Support ActiveRecord 7.0

---

lib/composite_primary_keys/validations/uniqueness.rb
test/fixtures/room_assignment.rb

Closes https://github.com/composite-primary-keys/composite_primary_keys/issues/578

Fix validate_each

---

test/test_create.rb

Related to: https://github.com/composite-primary-keys/composite_primary_keys/pull/586

Add an assertion for previously_new_record?

---

README.rdoc

Small grammatical correction in README.rdoc

---

.github/workflows/mariadb.yml
.github/workflows/mysql.yml
.github/workflows/postgresql.yml
.github/workflows/sqlite.yml
lib/composite_primary_keys/associations/association.rb
lib/composite_primary_keys/associations/association_scope.rb
test/connections/databases.ci.yml
test/fixtures/comments.yml
test/fixtures/db_definitions/mysql.sql
test/fixtures/user_with_polymorphic_name.rb
test/test_create.rb
test/test_polymorphic.rb

`polymorphic_name` was introduced in 5.2.0 but wasn't properly ported to CPK.

AR 5.2: Support polymorphic_name

---

Dockerfile
docker-compose.yml

To make development more convenient for others adding a Dockerfile and compose file seems reasonable. This way if/when an issue arises this will give everyone a place where they can rally to offer debugging help, etc.
- Add a Dockerfile 
- Add docker-compose.yml

Add docker and docker compose files
